name: cron-for-certbot
on:
  schedule:
    - cron:  '15 4 * * 3'
env:
  github_sha: ${{ github.sha }}
  ghToken: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - name: Pull in my docker images
      run: echo '::set-env name=TERM::xterm' && make pull-ngx
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCE_PROJECT_ID }}
        service_account_key: ${{ secrets.GCE_SERVICE_ACCOUNT_KEY }}
        service_account_email: ${{ secrets.GCE_SERVICE_ACCOUNT_EMAIL }}
        export_default_credentials: true
    - name: Renew Certs Every Week On Wednesday
      run: make cb-renew

