name: development-features
on:
  push:
    branches:
      - 'workflow'
      - 'feature/*'
      - '!master'
      - 'certbot/init'
env:
  github_sha: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
          fetch-depth: 1
    - name: Set environment variables
      run: |
          source .env
          echo '::set-env name=TERM::xterm'
