name: feature-development
on:
  push:
    branches:
      - 'feature/*'
      - '!main'
env:
  ghSha: ${{ github.sha }}
  ghToken: ${{ secrets.GITHUB_TOKEN }}
  TERM: xterm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCE_PROJECT_ID }}
        service_account_key: ${{ secrets.GCE_SERVICE_ACCOUNT_KEY }}
        service_account_email: ${{ secrets.GCE_SERVICE_ACCOUNT_EMAIL }}
        export_default_credentials: true
    - name: Run certbot on GCE and get certificate info
      run: make cb-info
      # - name: Fetch certs and put into 'letsencypt' volume on 'github-actions' host
      #run: |
      #    make gc-init
      #    make certs-into-vol
