name: continuous-integration
on:
  push:
    branches:
      - master
#https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onevent_nametypes
# environment variables available to all jobs and steps in this workflow
env:
  github_sha: ${{ github.sha }}
  UPLOAD_XQERL_COMPILED_CODE: 'true'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
          fetch-depth: 1
    - name: Set environment variables
      run: |
          echo '::set-env name=TERM::xterm'
          source .env
          source .version.env
          docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }} &>/dev/null
          echo ' - pull in main docker images'
          docker pull ${XQERL_DOCKER_IMAGE}:${XQ_VER}
          docker pull ${PROXY_DOCKER_IMAGE}:${NGX_VER}
          echo ' - pull in my docker images as helpers'
          docker pull docker.pkg.github.com/grantmacken/alpine-scour/scour:${SCOUR_VER}
          docker pull docker.pkg.github.com/grantmacken/alpine-zopfli/zopfli:${ZOPFLI_VER}
          docker pull docker.pkg.github.com/grantmacken/alpine-cssnano/cssnano:${CSSNANO_VER}
